import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import climateChangeHeaderWebp from './climateChangeHeader.webp';
import healthEnvironmentDayWebp from './0051424-R6-049-23.webp';
import muralBahrainWebp from './AO2 Bahrain. Islam Hasan (10 Bahrain).webp';
import muralNigeriaWebp from './AO4 Nigeria. Judith Yahaya 12.webp';
import muralUSAWebp from './AO5 USA. Alina Ponomarenko 11. The Camping Site.webp';
import muralPeruWebp from './Peru (Carla Guadalupe Gonzalez De La Cruz, 8).webp';
import muralAustriaWebp from './Austria (Samara Claudia Bittermann, 10).webp';

// avif imports (generated by vite-imagetools at build time)
import climateChangeHeaderAvif from './climateChangeHeader.webp?format=avif';
import healthEnvironmentDayAvif from './0051424-R6-049-23.webp?format=avif';
import muralBahrainAvif from './AO2 Bahrain. Islam Hasan (10 Bahrain).webp?format=avif';
import muralNigeriaAvif from './AO4 Nigeria. Judith Yahaya 12.webp?format=avif';
import muralUSAAvif from './AO5 USA. Alina Ponomarenko 11. The Camping Site.webp?format=avif';
import muralPeruAvif from './Peru (Carla Guadalupe Gonzalez De La Cruz, 8).webp?format=avif';
import muralAustriaAvif from './Austria (Samara Claudia Bittermann, 10).webp?format=avif';

export const climateChangeHeader: PictureSrc = {
  webp: climateChangeHeaderWebp,
  avif: climateChangeHeaderAvif,
};

export const healthEnvironmentDay: PictureSrc = {
  webp: healthEnvironmentDayWebp,
  avif: healthEnvironmentDayAvif,
};

export const muralBahrain: PictureSrc = {
  webp: muralBahrainWebp,
  avif: muralBahrainAvif,
};

export const muralNigeria: PictureSrc = {
  webp: muralNigeriaWebp,
  avif: muralNigeriaAvif,
};

export const muralUSA: PictureSrc = {
  webp: muralUSAWebp,
  avif: muralUSAAvif,
};

export const muralPeru: PictureSrc = {
  webp: muralPeruWebp,
  avif: muralPeruAvif,
};

export const muralAustria: PictureSrc = {
  webp: muralAustriaWebp,
  avif: muralAustriaAvif,
};
