import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import leadershipWorldMuralWebp from './worldMural.webp';

// avif imports (generated by vite-imagetools at build time)
import leadershipWorldMuralAvif from './worldMural.webp?format=avif';

export const leadershipWorldMural: PictureSrc = {
  webp: leadershipWorldMuralWebp,
  avif: leadershipWorldMuralAvif,
};
