import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import studentHeaderWebp from './studentHeader.webp';
import spreadCreativityWebp from './spreadCreativity.webp';

// avif imports (generated by vite-imagetools at build time)
import studentHeaderAvif from './studentHeader.webp?format=avif';
import spreadCreativityAvif from './spreadCreativity.webp?format=avif';

export const studentHeader: PictureSrc = {
  webp: studentHeaderWebp,
  avif: studentHeaderAvif,
};

export const spreadCreativity: PictureSrc = {
  webp: spreadCreativityWebp,
  avif: spreadCreativityAvif,
};
