import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import mfsHeaderWebp from './Arjaa Raghu (age 11) Illinois, USA 6.webp';
import submission1Webp from './submission-1.webp';
import submission2Webp from './submission-2.webp';
import mg8137Webp from './_MG_8137.webp';
import submission4Webp from './submission-4.webp';

// avif imports (generated by vite-imagetools at build time)
import mfsHeaderAvif from './Arjaa Raghu (age 11) Illinois, USA 6.webp?format=avif';
import submission1Avif from './submission-1.webp?format=avif';
import submission2Avif from './submission-2.webp?format=avif';
import mg8137Avif from './_MG_8137.webp?format=avif';
import submission4Avif from './submission-4.webp?format=avif';

export const mfsHeader: PictureSrc = {
  webp: mfsHeaderWebp,
  avif: mfsHeaderAvif,
};

export const submission1: PictureSrc = {
  webp: submission1Webp,
  avif: submission1Avif,
};

export const submission2: PictureSrc = {
  webp: submission2Webp,
  avif: submission2Avif,
};

export const mg8137: PictureSrc = {
  webp: mg8137Webp,
  avif: mg8137Avif,
};

export const submission4: PictureSrc = {
  webp: submission4Webp,
  avif: submission4Avif,
};
