services:
  localstack:
    image: localstack/localstack:latest
    container_name: icaf-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cognito-idp,dynamodb,iam,sts,s3
      - DEBUG=1
      - ENABLE_CORS=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5 