import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import dancingGirlWebp from './dancingGirl.webp';
import girlPaintHandsWebp from './girlPaintHands.webp';
import ourLegacyWebp from './ourLegacy.webp';
import congressWebp from './congress.webp';

// avif imports (generated by vite-imagetools at build time)
import dancingGirlAvif from './dancingGirl.webp?format=avif';
import girlPaintHandsAvif from './girlPaintHands.webp?format=avif';
import ourLegacyAvif from './ourLegacy.webp?format=avif';
import congressAvif from './congress.webp?format=avif';

export const dancingGirl: PictureSrc = {
  webp: dancingGirlWebp,
  avif: dancingGirlAvif,
};

export const girlPaintHands: PictureSrc = {
  webp: girlPaintHandsWebp,
  avif: girlPaintHandsAvif,
};

export const ourLegacy: PictureSrc = {
  webp: ourLegacyWebp,
  avif: ourLegacyAvif,
};

export const congress: PictureSrc = {
  webp: congressWebp,
  avif: congressAvif,
};
