import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import artShowcaseHeaderWebp from './ArtShowcaseHeader.webp';
import bannerImage1Webp from './BannerImage1.webp';
import bannerImage2Webp from './BannerImage2.webp';
import bannerImage3Webp from './BannerImage3.webp';
import bannerImage4Webp from './BannerImage4.webp';
import icafOverviewThumbWebp from './icaf-overview-cropped-thumb.webp';
import missionVisionLargeWebp from './MissionVisionLarge.webp';
import missionVisionSmallWebp from './MissionVisionSmall.webp';

// avif imports — desktop (generated by vite-imagetools at build time)
import artShowcaseHeaderAvif from './ArtShowcaseHeader.webp?format=avif';
import bannerImage1Avif from './BannerImage1.webp?format=avif';
import bannerImage2Avif from './BannerImage2.webp?format=avif';
import bannerImage3Avif from './BannerImage3.webp?format=avif';
import bannerImage4Avif from './BannerImage4.webp?format=avif';
import icafOverviewThumbAvif from './icaf-overview-cropped-thumb.webp?format=avif';
import missionVisionLargeAvif from './MissionVisionLarge.webp?format=avif';
import missionVisionSmallAvif from './MissionVisionSmall.webp?format=avif';

// avif imports — mobile (served below breakpoints.mobile via <Picture>)
// Header: portrait center-bottom crop at ~900×1125 (4:5) for narrow viewports
// Banners: width-capped at 1200px, no crop (they scroll horizontally so aspect ratio must be preserved)
import artShowcaseHeaderMobileAvif from './ArtShowcaseHeader.webp?w=900&h=1125&fit=cover&position=bottom&format=avif';
import bannerImage1MobileAvif from './BannerImage1.webp?w=1200&format=avif';
import bannerImage2MobileAvif from './BannerImage2.webp?w=1200&format=avif';
import bannerImage3MobileAvif from './BannerImage3.webp?w=1200&format=avif';
import bannerImage4MobileAvif from './BannerImage4.webp?w=1200&format=avif';

export const artShowcaseHeader: PictureSrc = {
  webp: artShowcaseHeaderWebp,
  avif: artShowcaseHeaderAvif,
  mobile: { avif: artShowcaseHeaderMobileAvif },
};

export const bannerImage1: PictureSrc = {
  webp: bannerImage1Webp,
  avif: bannerImage1Avif,
  mobile: { avif: bannerImage1MobileAvif },
};

export const bannerImage2: PictureSrc = {
  webp: bannerImage2Webp,
  avif: bannerImage2Avif,
  mobile: { avif: bannerImage2MobileAvif },
};

export const bannerImage3: PictureSrc = {
  webp: bannerImage3Webp,
  avif: bannerImage3Avif,
  mobile: { avif: bannerImage3MobileAvif },
};

export const bannerImage4: PictureSrc = {
  webp: bannerImage4Webp,
  avif: bannerImage4Avif,
  mobile: { avif: bannerImage4MobileAvif },
};

export const icafOverviewThumb: PictureSrc = {
  webp: icafOverviewThumbWebp,
  avif: icafOverviewThumbAvif,
};

export const missionVisionLarge = { webp: missionVisionLargeWebp, avif: missionVisionLargeAvif };
export const missionVisionSmall = { webp: missionVisionSmallWebp, avif: missionVisionSmallAvif };
