import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import artShowcaseHeaderWebp from './ArtShowcaseHeader.webp';
import bannerImage1Webp from './BannerImage1.webp';
import bannerImage2Webp from './BannerImage2.webp';
import bannerImage3Webp from './BannerImage3.webp';
import bannerImage4Webp from './BannerImage4.webp';
import icafOverviewThumbWebp from './icaf-overview-cropped-thumb.webp';
import missionVisionLargeWebp from './MissionVisionLarge.webp';
import missionVisionSmallWebp from './MissionVisionSmall.webp';

// avif imports (generated by vite-imagetools at build time)
import artShowcaseHeaderAvif from './ArtShowcaseHeader.webp?format=avif';
import bannerImage1Avif from './BannerImage1.webp?format=avif';
import bannerImage2Avif from './BannerImage2.webp?format=avif';
import bannerImage3Avif from './BannerImage3.webp?format=avif';
import bannerImage4Avif from './BannerImage4.webp?format=avif';
import icafOverviewThumbAvif from './icaf-overview-cropped-thumb.webp?format=avif';
import missionVisionLargeAvif from './MissionVisionLarge.webp?format=avif';
import missionVisionSmallAvif from './MissionVisionSmall.webp?format=avif';

export const artShowcaseHeader: PictureSrc = {
  webp: artShowcaseHeaderWebp,
  avif: artShowcaseHeaderAvif,
};

export const bannerImage1: PictureSrc = {
  webp: bannerImage1Webp,
  avif: bannerImage1Avif,
};

export const bannerImage2: PictureSrc = {
  webp: bannerImage2Webp,
  avif: bannerImage2Avif,
};

export const bannerImage3: PictureSrc = {
  webp: bannerImage3Webp,
  avif: bannerImage3Avif,
};

export const bannerImage4: PictureSrc = {
  webp: bannerImage4Webp,
  avif: bannerImage4Avif,
};

export const icafOverviewThumb: PictureSrc = {
  webp: icafOverviewThumbWebp,
  avif: icafOverviewThumbAvif,
};

export const missionVisionLarge = { webp: missionVisionLargeWebp, avif: missionVisionLargeAvif };
export const missionVisionSmall = { webp: missionVisionSmallWebp, avif: missionVisionSmallAvif };
