import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import worldMuralWebp from './WorldMural.webp';
import dancingWebp from './Dancing.webp';

// avif imports (generated by vite-imagetools at build time)
import worldMuralAvif from './WorldMural.webp?format=avif';
import dancingAvif from './Dancing.webp?format=avif';

export const worldMural: PictureSrc = {
  webp: worldMuralWebp,
  avif: worldMuralAvif,
};

export const dancing: PictureSrc = {
  webp: dancingWebp,
  avif: dancingAvif,
};
