import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import artsOlympiadHeroWebp from './arts-olympiad-hero.webp';
import artsOlympiadColoringWebp from './arts-olympiad-coloring.webp';
import artsOlympiadPaintingWebp from './arts-olympiad-painting.webp';

// avif imports (generated by vite-imagetools at build time)
import artsOlympiadHeroAvif from './arts-olympiad-hero.webp?format=avif';
import artsOlympiadColoringAvif from './arts-olympiad-coloring.webp?format=avif';
import artsOlympiadPaintingAvif from './arts-olympiad-painting.webp?format=avif';

export const artsOlympiadHero: PictureSrc = {
  webp: artsOlympiadHeroWebp,
  avif: artsOlympiadHeroAvif,
};

export const artsOlympiadColoring: PictureSrc = {
  webp: artsOlympiadColoringWebp,
  avif: artsOlympiadColoringAvif,
};

export const artsOlympiadPainting: PictureSrc = {
  webp: artsOlympiadPaintingWebp,
  avif: artsOlympiadPaintingAvif,
};
