import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import historyHeaderWebp from './HistoryHeader.webp';
import icafFoundingWebp from './ICAFFounding.webp';
import magazineCoverWebp from './MagazineCover.webp';
import dcMayorWebp from './DCMayor.webp';
import giraffeGroupWebp from './GiraffeGroup.webp';

// avif imports (generated by vite-imagetools at build time)
import historyHeaderAvif from './HistoryHeader.webp?format=avif';
import icafFoundingAvif from './ICAFFounding.webp?format=avif';
import magazineCoverAvif from './MagazineCover.webp?format=avif';
import dcMayorAvif from './DCMayor.webp?format=avif';
import giraffeGroupAvif from './GiraffeGroup.webp?format=avif';

export const historyHeader: PictureSrc = {
  webp: historyHeaderWebp,
  avif: historyHeaderAvif,
};

export const icafFounding: PictureSrc = {
  webp: icafFoundingWebp,
  avif: icafFoundingAvif,
};

export const magazineCover: PictureSrc = {
  webp: magazineCoverWebp,
  avif: magazineCoverAvif,
};

export const dcMayor: PictureSrc = {
  webp: dcMayorWebp,
  avif: dcMayorAvif,
};

export const giraffeGroup: PictureSrc = {
  webp: giraffeGroupWebp,
  avif: giraffeGroupAvif,
};
