import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import groupOfPeopleWebp from './group-of-people.webp';
import usCongressBackgroundWebp from './united-states-congress-background-flat-style 1.webp';

// avif imports (generated by vite-imagetools at build time)
import groupOfPeopleAvif from './group-of-people.webp?format=avif';
import usCongressBackgroundAvif from './united-states-congress-background-flat-style 1.webp?format=avif';

export const groupOfPeople: PictureSrc = {
  webp: groupOfPeopleWebp,
  avif: groupOfPeopleAvif,
};

export const usCongressBackground: PictureSrc = {
  webp: usCongressBackgroundWebp,
  avif: usCongressBackgroundAvif,
};
