import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import childArtMagazineWebp from './childArtMagazine.webp';
import healingArtsProgramWebp from './healingArtsProgram_smaller.webp';

// avif imports (generated by vite-imagetools at build time)
import childArtMagazineAvif from './childArtMagazine.webp?format=avif';
import healingArtsProgramAvif from './healingArtsProgram_smaller.webp?format=avif';

export const childArtMagazine: PictureSrc = {
  webp: childArtMagazineWebp,
  avif: childArtMagazineAvif,
};

export const healingArtsProgram: PictureSrc = {
  webp: healingArtsProgramWebp,
  avif: healingArtsProgramAvif,
};
