import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import image404Webp from './404Image.webp';

// avif imports (generated by vite-imagetools at build time)
import image404Avif from './404Image.webp?format=avif';

export const image404: PictureSrc = {
  webp: image404Webp,
  avif: image404Avif,
};
