import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import mapVideoCoverWebp from './map-video-cover.webp';
import rectangleHeartWebp from './rectangleHeart.webp';
import rectangleGlobeWebp from './rectangleGlobe.webp';
import rectangleHeartLargeWebp from './rectangleHeartLarge.webp';
import rectangleGlobeLargeWebp from './rectangleGlobeLarge.webp';
import icaf1Webp from './ICAF1.webp';
import ourProgramsWebp from './ourPrograms.webp';
import writingsResearchWebp from './writingsResearch.webp';
import unitedStatesSLKorthWebp from './UnitedStatesSLKorth.webp';
import aboutUsHeroWebp from './AboutUsHero.webp';

// avif imports (generated by vite-imagetools at build time)
import mapVideoCoverAvif from './map-video-cover.webp?format=avif';
import rectangleHeartAvif from './rectangleHeart.webp?format=avif';
import rectangleGlobeAvif from './rectangleGlobe.webp?format=avif';
import rectangleHeartLargeAvif from './rectangleHeartLarge.webp?format=avif';
import rectangleGlobeLargeAvif from './rectangleGlobeLarge.webp?format=avif';
import icaf1Avif from './ICAF1.webp?format=avif';
import ourProgramsAvif from './ourPrograms.webp?format=avif';
import writingsResearchAvif from './writingsResearch.webp?format=avif';
import unitedStatesSLKorthAvif from './UnitedStatesSLKorth.webp?format=avif';
import aboutUsHeroAvif from './AboutUsHero.webp?format=avif';

export const mapVideoCover: PictureSrc = {
  webp: mapVideoCoverWebp,
  avif: mapVideoCoverAvif,
};

export const rectangleHeart: PictureSrc = {
  webp: rectangleHeartWebp,
  avif: rectangleHeartAvif,
};

export const rectangleGlobe: PictureSrc = {
  webp: rectangleGlobeWebp,
  avif: rectangleGlobeAvif,
};

export const rectangleHeartLarge: PictureSrc = {
  webp: rectangleHeartLargeWebp,
  avif: rectangleHeartLargeAvif,
};

export const rectangleGlobeLarge: PictureSrc = {
  webp: rectangleGlobeLargeWebp,
  avif: rectangleGlobeLargeAvif,
};

export const icaf1: PictureSrc = {
  webp: icaf1Webp,
  avif: icaf1Avif,
};

export const ourPrograms: PictureSrc = {
  webp: ourProgramsWebp,
  avif: ourProgramsAvif,
};

export const writingsResearch: PictureSrc = {
  webp: writingsResearchWebp,
  avif: writingsResearchAvif,
};

export const unitedStatesSLKorth: PictureSrc = {
  webp: unitedStatesSLKorthWebp,
  avif: unitedStatesSLKorthAvif,
};

export const aboutUsHero: PictureSrc = {
  webp: aboutUsHeroWebp,
  avif: aboutUsHeroAvif,
};
