import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import healingArtsHeaderWebp from './healing-arts-header.webp';
import healingArtsThumbWebp from './healing-arts-thumb.webp';

// avif imports (generated by vite-imagetools at build time)
import healingArtsHeaderAvif from './healing-arts-header.webp?format=avif';
import healingArtsThumbAvif from './healing-arts-thumb.webp?format=avif';

export const healingArtsHeader: PictureSrc = {
  webp: healingArtsHeaderWebp,
  avif: healingArtsHeaderAvif,
};

export const healingArtsThumb: PictureSrc = {
  webp: healingArtsThumbWebp,
  avif: healingArtsThumbAvif,
};
