import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import icafGroupPhotoWebp from './icafGroupPhoto.webp';
import teamHeaderWebp from './teamHeader.webp';
import yellowFireworkWebp from './yellowFirework.webp';
import newYorkMichaelWongWebp from './New-York-_Michael-Wong_---11.webp';

// avif imports (generated by vite-imagetools at build time)
import icafGroupPhotoAvif from './icafGroupPhoto.webp?format=avif';
import teamHeaderAvif from './teamHeader.webp?format=avif';
import yellowFireworkAvif from './yellowFirework.webp?format=avif';
import newYorkMichaelWongAvif from './New-York-_Michael-Wong_---11.webp?format=avif';

export const icafGroupPhoto: PictureSrc = {
  webp: icafGroupPhotoWebp,
  avif: icafGroupPhotoAvif,
};

export const teamHeader: PictureSrc = {
  webp: teamHeaderWebp,
  avif: teamHeaderAvif,
};

export const yellowFirework: PictureSrc = {
  webp: yellowFireworkWebp,
  avif: yellowFireworkAvif,
};

export const newYorkMichaelWong: PictureSrc = {
  webp: newYorkMichaelWongWebp,
  avif: newYorkMichaelWongAvif,
};
