import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import wcaHeaderWebp from './wca-header.webp';
import congressImgWebp from './congress-img.webp';
import wcaContentImg1Webp from './wca-content-img1.webp';

// avif imports (generated by vite-imagetools at build time)
import wcaHeaderAvif from './wca-header.webp?format=avif';
import congressImgAvif from './congress-img.webp?format=avif';
import wcaContentImg1Avif from './wca-content-img1.webp?format=avif';

export const wcaHeader: PictureSrc = {
  webp: wcaHeaderWebp,
  avif: wcaHeaderAvif,
};

export const congressImg: PictureSrc = {
  webp: congressImgWebp,
  avif: congressImgAvif,
};

export const wcaContentImg1: PictureSrc = {
  webp: wcaContentImg1Webp,
  avif: wcaContentImg1Avif,
};
