import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import professionalsHeaderWebp from './professionals.webp';
import faceCollageWebp from './pexels-vanessa-loring-7869442 3.webp';

// avif imports (generated by vite-imagetools at build time)
import professionalsHeaderAvif from './professionals.webp?format=avif';
import faceCollageAvif from './pexels-vanessa-loring-7869442 3.webp?format=avif';

export const professionalsHeader: PictureSrc = {
  webp: professionalsHeaderWebp,
  avif: professionalsHeaderAvif,
};

export const faceCollage: PictureSrc = {
  webp: faceCollageWebp,
  avif: faceCollageAvif,
};
