import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import aboutHeroWebp from './_MG_5720.webp';

// avif imports (generated by vite-imagetools at build time)
import aboutHeroAvif from './_MG_5720.webp?format=avif';

export const aboutHero: PictureSrc = {
  webp: aboutHeroWebp,
  avif: aboutHeroAvif,
};
