export const DEFAULT_THEME_VISUAL_DURATION_SECONDS = 7.2;
export const GALLERY_THEME_CARD_HEIGHT_CLASS = 'h-[80px]';
export const GALLERY_THEME_CARD_WIDTH_CLASS = 'w-[300px]';
export const GALLERY_THEME_VISUAL_SIZE_CLASS = `${GALLERY_THEME_CARD_HEIGHT_CLASS} ${GALLERY_THEME_CARD_WIDTH_CLASS}`;
