import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import volunteerHeaderWebp from './volunteerHeader.webp';
import volunteerGroupWebp from './volunteerGroup.webp';
import icaf3Webp from './icaf3.webp';
import connecticutArtWebp from './Conneticut (Jazmine Anderson, 11).webp';

// avif imports (generated by vite-imagetools at build time)
import volunteerHeaderAvif from './volunteerHeader.webp?format=avif';
import volunteerGroupAvif from './volunteerGroup.webp?format=avif';
import icaf3Avif from './icaf3.webp?format=avif';
import connecticutArtAvif from './Conneticut (Jazmine Anderson, 11).webp?format=avif';

export const volunteerHeader: PictureSrc = {
  webp: volunteerHeaderWebp,
  avif: volunteerHeaderAvif,
};

export const volunteerGroup: PictureSrc = {
  webp: volunteerGroupWebp,
  avif: volunteerGroupAvif,
};

export const icaf3: PictureSrc = {
  webp: icaf3Webp,
  avif: icaf3Avif,
};

export const connecticutArt: PictureSrc = {
  webp: connecticutArtWebp,
  avif: connecticutArtAvif,
};
