import type { PictureSrc } from '@/components/shared/Picture';

// webp imports (source of truth)
import galleryHeaderWebp from './gallery-header.webp';

// avif imports (generated by vite-imagetools at build time)
import galleryHeaderAvif from './gallery-header.webp?format=avif';

export const galleryHeader: PictureSrc = {
  webp: galleryHeaderWebp,
  avif: galleryHeaderAvif,
};
